name: React Native CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test

      - name: Set execute permission for gradlew
        run: |
          chmod +x android/gradlew

      - name: Build Debug APK for Android
        run: |
          npx react-native bundle --platform android --dev true --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
          cd android
          ./gradlew assembleDebug

      - name: Upload Debug APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: debug-android
          path: android/app/build/outputs/apk/debug/*.apk

      - name: Set up Xcode tools
        uses: r0man/xcode@v2

      - name: Checkout code for iOS
        uses: actions/checkout@v2
        with:
          repository: 'path/to/your/ios/project'  # Update with your iOS project repository

      - name: Set up CocoaPods
        run: |
          cd ios
          gem install cocoapods
          pod install
          pod deintegrate
          pod install

      - name: Build Debug IPA for iOS
        run: |
          xcodebuild -workspace cicd.xcworkspace -scheme cicd -destination generic/platform=iOS -configuration Debug clean archive -archivePath build/cicd.xcarchive CODE_SIGN_STYLE=Automatic CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= PROVISIONING_PROFILE= || true
          xcodebuild -exportArchive -archivePath build/cicd.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/cicd
          mv build/cicd/*.ipa ../debug-ios.ipa

      - name: Upload Debug IPA artifact
        uses: actions/upload-artifact@v2
        with:
          name: debug-ios
          path: debug-ios.ipa
