name: React Native CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test

      # - name: Set execute permission for gradlew
      #   run: |
      #     chmod +x android/gradlew

      # - name: Build Debug APK for Android
      #   run: |
      #     npx react-native bundle --platform android --dev true --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
      #     cd android
      #     ./gradlew assembleDebug

      # - name: Upload Debug APK artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: debug-android
      #     path: android/app/build/outputs/apk/debug/*.apk

      - name: Prepare for iOS Build
        run: |
          echo "Preparing for iOS Build..."
          echo "Installing CocoaPods..."
          sudo gem install cocoapods
          cd ios
          pod install

      - name: Create IPA
        run: |
          echo "Creating IPA..."
          echo "Build the project using Xcode or run a script"
          echo "For example, you can create a simple script like 'build_ipa.sh' in the ios folder"
          echo "Contents of 'build_ipa.sh':"
          echo "#!/bin/bash"
          echo "xcodebuild -workspace cicd.xcworkspace -scheme cicd -configuration Debug -destination 'generic/platform=iOS' archive -archivePath build/cicd.xcarchive CODE_SIGN_STYLE=Automatic CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= PROVISIONING_PROFILE="
          echo "xcodebuild -exportArchive -archivePath build/cicd.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/cicd"
          echo "mv build/cicd/*.ipa ../debug-ios.ipa"
          echo "chmod +x build_ipa.sh"
          echo "./build_ipa.sh"

      - name: Upload Debug IPA artifact
        uses: actions/upload-artifact@v2
        with:
          name: debug-ios
          path: debug-ios.ipa
