name: React Native CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test

      - name: Set execute permission for gradlew
        run: |
          chmod +x android/gradlew

      - name: Build Debug APK for Android
        run: |
          npx react-native bundle --platform android --dev true --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
          cd android
          ./gradlew assembleDebug

      - name: Upload Debug APK artifact for Android
        uses: actions/upload-artifact@v2
        with:
          name: debug-android
          path: android/app/build/outputs/apk/debug/*.apk

      - name: Build Debug IPA for iOS
        run: |
          npx react-native bundle --platform ios --dev true --entry-file index.js --bundle-output ios/main.jsbundle --assets-dest ios
          cd ios
          xcodebuild -workspace YourProject.xcworkspace -scheme YourProject -configuration Debug -sdk iphoneos clean archive -archivePath build/YourProject
          xcodebuild -exportArchive -archivePath "build/YourProject.xcarchive" -exportPath "build" -exportOptionsPlist "ExportOptions.plist"

      - name: Upload Debug IPA artifact for iOS
        uses: actions/upload-artifact@v2
        with:
          name: debug-ios
          path: ios/build/*.ipa

      - name: Build Release AAB for Android
        run: |
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
          cd android
          ./gradlew bundleRelease

      - name: Upload Release AAB artifact for Android
        uses: actions/upload-artifact@v2
        with:
          name: release-android
          path: android/app/build/outputs/bundle/release/*.aab

      - name: Build Release IPA for iOS
        run: |
          npx react-native bundle --platform ios --dev false --entry-file index.js --bundle-output ios/main.jsbundle --assets-dest ios
          cd ios
          xcodebuild -workspace YourProject.xcworkspace -scheme YourProject -configuration Release -sdk iphoneos clean archive -archivePath build/YourProject
          xcodebuild -exportArchive -archivePath "build/YourProject.xcarchive" -exportPath "build" -exportOptionsPlist "ExportOptions.plist"

      - name: Upload Release IPA artifact for iOS
        uses: actions/upload-artifact@v2
        with:
          name: release-ios
          path: ios/build/*.ipa
