name: React Native CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test

      - name: Prepare for iOS Build
        run: |
          echo "Preparing for iOS Build..."
          echo "Installing CocoaPods..."
          sudo gem install cocoapods
          cd ios
          echo "platform :ios, '12.0'" > Podfile
          echo "use_modular_headers!" >> Podfile
          echo "target 'CICD' do" >> Podfile
          echo "end" >> Podfile
          # Add other pods as needed
          pod install

      - name: Create IPA
        run: |
          echo "Creating IPA..."
          echo "Build the project using Xcode or run a script"
          echo "For example, you can create a simple script like 'build_ipa.sh' in the ios folder"
          echo "Contents of 'build_ipa.sh':"
          echo "#!/bin/bash"
          echo "xcodebuild -workspace CICD.xcworkspace -scheme CICD -configuration Debug -destination 'generic/platform=iOS' archive -archivePath build/cicd.xcarchive CODE_SIGN_STYLE=Automatic CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= PROVISIONING_PROFILE="
          echo "xcodebuild -exportArchive -archivePath build/cicd.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/cicd"
          echo "ls -l build/cicd/*.ipa"
          echo "mv build/cicd/*.ipa ../debug-ios.ipa"
          echo "chmod +x build_ipa.sh"
          echo "./build_ipa.sh"

      - name: Move IPA File
        run: |
          ls -l
          ls -l ios
          mv debug-ios.ipa ios/debug-ios.ipa

      - name: List IPA Files
        run: |
          ls -l ios/debug-ios.ipa

      - name: Upload Debug IPA artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: debug-ios
          path: ios/debug-ios.ipa
