name: React Native CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test

      - name: Set execute permission for gradlew
        run: |
          chmod +x android/gradlew

      - name: Build Debug APK for Android
        run: |
          npx react-native bundle --platform android --dev true --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
          cd android
          ./gradlew assembleDebug

      - name: Upload Debug APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: debug-android
          path: android/app/build/outputs/apk/debug/*.apk

      - name: Prepare for iOS Build
        run: |
          echo "Prepare for iOS Build"

      - name: Upload iOS Build Configuration
        uses: actions/upload-artifact@v2
        with:
          name: ios-build-config
          path: ios

      - name: Upload Debug IPA Template
        uses: actions/upload-artifact@v2
        with:
          name: debug-ios-template
          path: .github/workflows/debug-ios-template

