name: React Native CI/CD

on:
  push:
    branches:
      - Bhavdip_Dev
      - Production
      - Deployment

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Install dependencies
        run: npm install

      - name: Build Debug APK (Bhavdip_Dev branch)
        if: github.ref == 'refs/heads/Bhavdip_Dev'
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Build Release APK (Production branch)
        if: github.ref == 'refs/heads/Production'
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Generate AAB (Deployment branch)
        if: github.ref == 'refs/heads/Deployment'
        run: |
          chmod +x ./generate-aab.sh
          ./generate-aab.sh

      - name: Archive AAB artifact
        if: github.ref == 'refs/heads/Bhavdip_Dev' || github.ref == 'refs/heads/Production' || github.ref == 'refs/heads/Deployment'
        uses: actions/upload-artifact@v2
        with:
          name: android-artifacts
          path: android/app/build/outputs/bundle/release/app-release.aab
